# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            fingerection
tagline:          'feel relax when coding'
description:      '本博客记录日常技术工作中碰到的问题和解决方案，包括不限于JS，Python，Linux系统，数据分析'
url:              https://fingerection.github.io/blog/
baseurl:          /blog

author:
  name:           'fingerection'
  url:            https://twitter.com/fingerection

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fingerection/blog

# Gems
gems: [jekyll-paginate]
